sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t sumitbhavra/prod_react_app -f Dockerfile.dev .

script:
  - docker run -e CI=true sumitbhavra/prod_react_app  npm run test