sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t sumitbhavra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sumitbhavra/docker-react  npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-466019163455"
    bucket_path: "docker_react"
    on: 
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"